version: '3.8'
name: soa-projekat
services:
  microservice-db:
    image: microservice-db:latest
    build:
      context: ./MicroService-DB
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - PORT=5000
  microservice-gateway:
    image: microservice-gateway:latest
    build:
      context: ./MicroService-Gateway
      dockerfile: ./Dockerfile
    ports:
      - 5170:5170
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - microservice-db
