version: '3.8'

name: 'soa-projekat-1-2'
services:
  service-db:
    image: microservicedb
    build: ./MicroService-DB
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
  service-gateway:
    image: microservicegateway
    build: ./MicroService-Gateway
    depends_on:
      - mqtt
    environment:
      ASPNETCORE_ENVIRONMENT: development
    ports:
      - 5170:5170
    volumes:
      - ./Datasets:/home/datasets:ro
  service-analytics:
    image: microserviceanalytics
    build: ./MicroService-analytics
    depends_on:
      - mqtt
      - service-notif
  service-notif:
    image: microservicenotif
    build: ./MicroService-Notif
    environment:
      NODE_ENV: production
    ports:
      - 8085:8085
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./volumes/config:/mosquitto/config
    ports:
      - 1883:1883
      - 9001:9001
  kuiper:
    container_name: kuiper
    image: lfedge/ekuiper:1.5.1-alpine
    restart: always
    ports:
      - 9081:9081
  kuiperManager:
    container_name: kuiperManager
    image: emqx/ekuiper-manager:1.5
    restart: always
    ports:
      - 9082:9082
    
